export const FETCH_STORIES = 'FETCH_STORIES'
export const EDIT_STORY = 'EDIT_STORY'
export const UPDATE_STORY = 'UPDATE_STORY'
export const ADD_STORY = 'ADD_STORY'
export const DELETE_STORY = 'DELETE_STORY'
